# Generated by Django 5.2.1 on 2025-06-12 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supportpost_votes_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisisresource',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='crisisresource',
            name='website',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='supportpost',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='crisisresource',
            name='contact_info',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='crisisresource',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='crisisresource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportpost',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
