# Generated by Django 5.2.1 on 2025-06-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supportpost_upvoted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportpost',
            name='upvoted_by',
        ),
    ]
