# Generated by Django 5.2.1 on 2025-06-13 02:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_supportpost_upvoted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
