# Generated by Django 5.2.1 on 2025-06-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reply_upvoted_by_reply_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisisresource',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='crisisresource',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crisisresource',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crisisresource',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crisisresource',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
